-- Создаем таблицу People
CREATE TABLE People(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login TEXT,
    password TEXT,
    email TEXT,
    telephone TEXT,
    tgLink TEXT
);

-- Создаем таблицу Project
CREATE TABLE Project(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT,
    description TEXT,
    telegramLink TEXT,
    slackLink TEXT,
    emailTeamLead TEXT
);

-- Создаем таблицу PeopleInProject
CREATE TABLE PeopleInProject(
    idProject INT REFERENCES Project(id),
    idPeople INT REFERENCES People(id),
    role TEXT,
    PRIMARY KEY(idProject, idPeople)
);
