name: PMDv2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze:
    name: Analyze code with CodeQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          
      - name: Build with Maven
        run: mvn clean install -DskipTests=true
      
      - name: Run PMD
        run: |
          mvn pmd:pmd
          if grep -q 'com/AlertSystem' backendSiteDiplom/target/site/pmd.html; then
            echo "String 'com/AlertSystem' found in PMD report."
            exit 1
          fi
      
      - name: Save PMD results
        run: |
          mkdir -p pmd-results
          mv backendSiteDiplom/target/site/pmd.html pmd-results/
        continue-on-error: true
      
      - name: List files in directory
        run: ls -R
      
      - name: Upload PMD results
        uses: actions/upload-artifact@v2
        with:
          name: pmd-results
          path: pmd-results

  artifacts:
    runs-on: ubuntu-latest
    needs: [analyze]
    steps:
      - name: Archive PMD results
        uses: actions/upload-artifact@v2
        with:
          name: pmd-results
          path: pmd-results

